// getProducts
export const  GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const  GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const  GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

// getProducts by ID 
export const GET_PRODUCT_BY_ID_REQUEST = 'GET_PRODUCT_BY_ID_REQUEST';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';
export const GET_PRODUCT_BY_ID_FAILED = 'GET_PRODUCT_BY_ID_FAILED';